OTS_APP/urls.py
from django.urls import path
from OTS_APP.views import *
app_name='OTS_APP'
urlpatterns=[
  path("",welcome),
  path("new-candidate",CandidateRegistrationForm,name="RegistrationForm"),
  path("store-candidate",CandidateRegistration,name="Registration"),
  path("login",Loginview,name="login"),
  path("home",CandidateHome,name="home"),
  path("test-paper",TestPaper,name="TestPaper"),
  path("calculate-result",CalculateTestResult,name="CalculateResult"),
  path("TestResult",ShowTestResult,name="TestResult"),
  path("result-history",TestResultHistory,name='TestHistory'),
  path("logout",Logout,name="logout"),
]

webproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("",include('OTS_APP.urls')),
    path('admin/', admin.site.urls),
]

OTS_APP/models.py
from django.db import models

class Candidate(models.Model):
    Username=models.CharField(primary_key=True,max_length=255)
    Password=models.CharField(null=False,max_length=255)
    Name=models.CharField(null=False,max_length=255)
    Test_attempt=models.IntegerField(default=0)
    Points=models.FloatField(default=0)
    def __str__(self):
        return self.Name
class Question(models.Model):
    Queid=models.BigAutoField(primary_key=True,auto_created=True)
    Que=models.TextField()
    a=models.CharField(max_length=255)
    b=models.CharField(max_length=255)
    c=models.CharField(max_length=255)
    d=models.CharField(max_length=255)
    Ans=models.CharField(max_length=2)
  
class Result(models.Model):
    Resultid=models.BigAutoField(primary_key=True,auto_created=True)
    Username=models.ForeignKey(Candidate,on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)
    attempt=models.IntegerField()
    Right=models.IntegerField()
    Wrong=models.IntegerField()
    points=models.FloatField()
 

OTS_APP/views.py
from django.shortcuts import render
from django.template import loader
from OTS_APP.models import *
from django.http import HttpResponse,HttpResponseRedirect
import random

def welcome(requset):
    temp=loader.get_template('welcome.html')
    return HttpResponse(temp.render())
def CandidateRegistrationForm(request):
    return render(request,"registration_form.html")
def CandidateRegistration(request):
    if request.method=="POST":
        username=request.POST["username"]
        if (len(Candidate.objects.filter(Username=username))):
            userstatus=1
        else:
            candidate=Candidate()
            candidate.Username=username
            candidate.Password=request.POST["password"]
            candidate.Name=request.POST["name"]
            candidate.save()
            userstatus=2
    else:
        userstatus=3
    return render(request,"RegistrationStatus.html",{'userstatus':userstatus})
def Loginview(request):
   if request.method=="POST":
       username=request.POST['username']
       password=request.POST['password']
      
       candidate=Candidate.objects.filter(Username=username,Password=password)
    
       if(len(candidate)==0):
           logerror="invalid username or password"
           res=render(request,"login.html",{'loginerror':logerror})
       else:
           request.session['username']=candidate[0].Username
           request.session['name']=candidate[0].Name
           res=HttpResponseRedirect("home")
   else:
       res=render(request,"login.html") 
   return res
def CandidateHome(request):
   if 'name' not in request.session.keys():
       return HttpResponseRedirect("login")
   else:
       return render(request,"home.html")
def TestPaper(request):
   if 'name' not in request.session.keys():
       return HttpResponseRedirect('login')

   n=int(request.GET['n'])
   question_pool=list(Question.objects.all())
   random.shuffle(question_pool)
   question_list=question_pool[:n]
   return render(request,'TestPaper.html',{'questions':question_list})
   
def CalculateTestResult(request):
     if 'name' not in request.session.keys():
       return HttpResponseRedirect('login')
     total_attempt=0  
     total_right=0
     total_wrong=0
     qid_list=[]
     for k in request.POST:
         if k.startswith('q'):
                  try:
                    qid_list.append(int(request.POST[k]))
                  except:
                      pass
          
     for n in qid_list:
         question=Question.objects.get(Queid=n)
         try:
             if question.Ans==request.POST['q'+str(n)]:
                 total_right+=1
             else:
                 total_wrong+=1
             total_attempt+=1
         except:
            pass
     points=(total_right-total_wrong)*2
     result=Result()
     result.Username=Candidate.objects.get(Username=request.session['username'])
     result.attempt=total_attempt
     result.Right=total_right
     result.Wrong=total_wrong
     result.points=points
     result.save()
     #update candidate
     candidate=Candidate.objects.get(Username=request.session['username'])
     candidate. Test_attempt+=1
     candidate.Points=(candidate.Points*(candidate.Test_attempt-1)+points)
     candidate.save()
     return HttpResponseRedirect('TestResult')
     
 
             

def ShowTestResult(request):
    if 'name' not in request.session.keys():
        return HttpResponseRedirect('login')
    result=Result.objects.filter(Resultid=Result.objects.latest('Resultid').Resultid)
    return render(request,'show_result.html',{'context':result})
   
def TestResultHistory(request):
     if 'name' not in request.session.keys():
        return HttpResponseRedirect('login')
     candidate=Candidate.objects.filter(Username=request.session['username']) 
     results=Result.objects.filter(Username=candidate[0].Username)
     context2={'candidate':candidate[0],'result':results}
     return render(request,"candidate_history.html",context2)
  
def Logout(request):
  if 'name'  in request.session.keys():
      del request.session['username']
      del request.session['name']
      return HttpResponseRedirect('login')

OTS_APP/templates/RegistrationStatus.html
{% extends 'master.html' %}
{% block title %}
 OTS- Registration status
{% endblock %}
{% block top %}
<a href="{% url 'OTS_APP:RegistrationForm' %}">SignUp</a>
<a href="{% url 'OTS_APP:login' %}">Login</a>
{% endblock %}
{% block content %}
  {% if userstatus == 1 %}
   <div class="userstatus">
     sorry!user alredy exists ,use another username
     <a href="{% url 'OTS_APP:RegistrationForm' %}"></a>
   </div>
   {% elif userstatus == 2 %}
   <div class="userstatus">
     congratulations!user successfully create
     <a href="{% url 'OTS_APP:login' %}"></a>
   </div>
   {% elif userstatus == 3 %}
   <div class="userstatus">
     oops! improper request
     <a href="{% url 'OTS_APP:RegistrationForm' %}"></a>
   </div>
{% endif %}
{% endblock %}

OTS_APP/templates/TestPaper.html
{% extends 'master.html' %}
{% block title %}OTS-TestPaper{% endblock %}
{% block top %}{% endblock %}
{% block content %}
  <form action="{% url 'OTS_APP:CalculateResult' %}" method="post">
          {% csrf_token %}
    {% for question in questions %}
    <div class="question">
        <input type="hidden" name="qno{{question.Queid}}" value="{{question.Que}}">
        {{question.Que}}
    </div>
 
<div class="options"><input type="radio" name="q{{question.Queid}}" value="a">{{question.a}}</div>
<div class="options"><input type="radio" name="q{{question.Queid}}" value="b">{{question.b}}</div>
<div class="options"><input type="radio" name="q{{question.Queid}}" value="c">{{question.c}}</div>
<div class="options"><input type="radio" name="q{{question.Queid}}" value="d">{{question.d}}</div>
{% endfor %}
<input type="submit" value="submit">
  </form>
{% endblock %}

OTS_APP/templates/candidate_history.html
{% extends 'master.html' %}
{% block title %}welcome to online testing system {% endblock %}
{% block top %}
<a href="{% url 'OTS_APP:home' %}">HOME</a>
<a href="{% url 'OTS_APP:logout' %}">LOGOUT</a>
{% endblock %}
{% block content %}
  <h1>YOUR REPORT CARD</h1>
  <h3>hi {{candidate.name}},you have attemped in total {{candidate.Test_attemped}} test and you have score {{candidate.Points}} on the scale of 20 </h3>
 <table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {% for i in result %}
    <tr>
        <td>{{i.date}}</td>
        <td>{{i.time}}</td>
        <td>{{i.attempt}}</td>
        <td>{{i.Right}}</td>
        <td>{{i.Wrong}}</td>
        <td>{{i.Points}}</td>
    </tr>
    {% endfor %}
   </table>
{% endblock %}

OTS_APP/templates/home.html
{% extends 'master.html' %}
{% block title %}OTS-Candidate Home Page{% endblock %}
{% block top %}
   <a href="{% url 'OTS_APP:RegistrationForm' %}">SignUp</a>
   <a href="{% url 'OTS_APP:logout' %}">LogOut</a>
{% endblock %}
{% block content %}
  <h1>welcome {{request.session.name}} to your home page</h1>
  <div class="button-link">
    <a href="{% url 'OTS_APP:TestPaper' %}?n=2">test of 2 question</a>
  </div>
  <div class="button-link">
    <a href="{% url 'OTS_APP:TestPaper' %}?n=3">test of 3 question</a>
  </div>
  <div class="button-link">
    <a href="{% url 'OTS_APP:TestPaper' %}?n=4">test of 4 question</a>
  </div>
  <div class="button-link">
    <a href="{% url 'OTS_APP:TestHistory' %}">TestHistory</a>
  </div>

{% endblock %}

OTS_APP/templates/login.html
{% extends 'master.html' %}
{% block title %}OTS-Login Form{% endblock %}
{% block top %}
   <a href="{% url 'OTS_APP:RegistrationForm' %}">SignUp</a>
{% endblock %}
{% block content %}
  <div class="all-forms">
    <form action="{% url 'OTS_APP:login' %}" method="post">
        {% csrf_token %}
        <div class="form-unit">
            {{loginerror}}
            <label for="username">USERNAME:</label>
            <input type="text" name="username">
        </div>
        <div class="form-unit">
            <label for="password">PASSWORD:</label>
            <input type="password" name="password">
        </div>
        <div class="form-unit">
           
            <input type="submit" value="submit">
            <input type="reset" name="" id="" value="clear">
        </div>


    </form>
  </div>

{% endblock %}

OTS_APP/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'theme.css' %}">
    <link rel="stylesheet" href="{% static 'forms.css' %}">
</head>
<body>
    <div class="top">
        <div class="sitename"><h1>ONLINE TESTING SYSTEM</h1></div>
          
            <div class="menu">
              {% block top %}{% endblock %}
            </div>
    </div>
    <div class="content">
       {% block content %}{% endblock %}
    </div>
</body>
</html>

OTS_APP/templates/registration_form.html
{% extends 'master.html' %}
{% block title %}OTS-Registration Form{% endblock %}
{% block top %}
<a href="{% url 'OTS_APP:login' %}">Login</a>
{% endblock %}
{% block content %}
  <div class="all-forms">
    <form action="{% url 'OTS_APP:Registration' %}" method="post">
        {% csrf_token %}
        <label for="username">USERNAME:</label>
        <input type="text" name="username">
        <label for="name">NAME:</label>
        <input type="text" name="name">
        <label for="password">PASSWORD:</label>
        <input type="password" name="password">

        <input type="submit" value="submit">
        <input type="reset" value="reset">
    </form>

  </div>
{% endblock %}

OTS_APP/templates/show_result.html
{% extends 'master.html' %}
{% block title %}welcome to online testing system {% endblock %}
{% block top %}
<a href="{% url 'OTS_APP:home' %}">HOME</a>
<a href="{% url 'OTS_APP:logout' %}">LOGOUT</a>
{% endblock %}
{% block content %}
   <table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {% for i in context %}
    <tr>
        <td>{{i.date}}</td>
        <td>{{i.time}}</td>
        <td>{{i.attempt}}</td>
        <td>{{i.Right}}</td>
        <td>{{i.Wrong}}</td>
        <td>{{i.Points}}</td>
    </tr>
    {% endfor %}
   </table>
{% endblock %}

OTS_APP/templates/welcome.html
{% extends 'master.html' %}
{% block title %}welcome to online testing system {% endblock %}
{% block top %}
<a href="{% url 'OTS_APP:RegistrationForm' %}">SignUp</a>
<a href="{% url 'OTS_APP:login' %}">Login</a>
{% endblock %}
{% block content %}
<p>Welcome To Online Testing System</p>
{% endblock %}